Repository wecode-bootcamp-korea/fullstack1-1st-BaseNote-frontend, pull requests merged in 2021-07, with the labels that each got.

#1 [오송미] README 파일 수정
  README.md
Labels: Status: Accepted

#7 [감하영] 초기세팅 수정 및 Container 컴포넌트 작성, 폴더 구조 수정 완료
  .prettierrc.json
  src/Routes.jsx
  src/assets/logo-BASENOTE.svg
  src/assets/logo-BASENOTE_all.svg
  src/assets/logo-BASENOTE_icon.svg
  src/assets/logo-BASENOTE_slogan.svg
  src/components/Container/Container.jsx
  src/components/Container/Container.scss
  src/pages/product/Product.jsx
  src/pages/product/ProductDetailHead/ProductDetailHead.jsx
  src/pages/product/ProductDetailHead/ProductDetailHead.scss
  src/pages/product/ProductDetailInfo/ProductDetailInfo.jsx
  src/pages/product/ProductDetailInfo/ProductDetailInfo.scss
  src/pages/product/ProductReview/ProductReview.jsx
  src/pages/product/ProductReview/ProductReview.scss
  src/styles/_reset.scss
  src/styles/_variables.scss
Labels: Status: 리뷰 요청

#9 [감하영] 장바구니 페이지 레이아웃 구현중
  src/Routes.jsx
  src/assets/logo-NAVER.svg
  src/pages/order/Cart/BuyButtons.jsx
  src/pages/order/Cart/BuyButtons.scss
  src/pages/order/Cart/Cart.jsx
  src/pages/order/Cart/Cart.scss
  src/pages/order/Cart/CartTable.jsx
  src/pages/order/Cart/CartTable.scss
  src/pages/order/Cart/CartTableDataRow.jsx
  src/pages/order/Cart/CartTableDataRow.scss
  src/pages/order/Cart/CartTableHeadRow.jsx
  src/pages/order/Cart/CartTableHeadRow.scss
  src/pages/order/Cart/TotalPriceTable.jsx
  src/pages/order/Cart/TotalPriceTable.scss
  src/pages/order/Cart/TotalPriceTableDataRow.jsx
  src/pages/order/Cart/TotalPriceTableDataRow.scss
  src/pages/order/Cart/TotalPriceTableHeadRow.jsx
  src/pages/order/Cart/TotalPriceTableHeadRow.scss
  src/pages/order/Order.jsx
  src/pages/order/Order.scss
  src/pages/order/index.jsx
  src/styles/_mixins.scss
  src/styles/_reset.scss
Labels: Status: 기능 구현 중, Status: 리뷰 요청

#4 [박미정] 제품 리스트의 제품 카드 컴포넌트 맵으로 데이터 받아오기 구현중
  public/data/mockdata.json
  src/index.jsx
  src/pages/category/Category.jsx
  src/pages/category/Category.scss
  src/pages/category/Components/ProductCard/ProductCard.jsx
  src/pages/category/Components/ProductCard/ProductCard.scss
  src/styles/common.scss
Labels: Status: 기능 구현 중, Status: 리뷰 요청

#11 [김민성] Top nav State 수정 완료
  public/mockdata.jsx
  src/components/Container/Container.jsx
  src/components/TopNav/TopNav.jsx
  src/pages/main/Main.jsx
Labels: Status: 리뷰 요청

#8 [오송미] 회원가입 레이아웃 완료
  package-lock.json
  package.json
  src/Routes.jsx
  src/pages/member/Login/Login.jsx
  src/pages/member/Login/Login.scss
  src/pages/member/Login/LoginForm.jsx
  src/pages/member/Login/LoginForm.scss
  src/pages/member/Member.jsx
  src/pages/member/Signup.jsx
  src/pages/member/Signup/Signup.jsx
  src/pages/member/Signup/Signup.scss
  src/pages/member/Signup/SignupForm.jsx
  src/pages/member/Signup/SignupForm.scss
  src/pages/member/index.jsx
  src/pages/order/Order.jsx
Labels: Status: 기능 구현 중, Status: 리뷰 요청

#13 MODIFY: 상품 디테일 페이지로 가는 라우팅 수정
  src/pages/category/Components/ProductCard/ProductCard.jsx
Labels: Status: 리뷰 요청

#10 [김민성] product detail head구현완료, SCSS수정
  .gitignore
  src/assets/square_naver_icon.png
  src/components/Container/Container.scss
  src/components/TopNav/TopNav.jsx
  src/pages/main/Main.jsx
  src/pages/product/Product.jsx
  src/pages/product/ProductDetailHead/ProductDetailBigVolumeHead.jsx
  src/pages/product/ProductDetailHead/ProductDetailBigVolumeHead.scss
  src/pages/product/ProductDetailHead/ProductDetailHead.jsx
  src/pages/product/ProductDetailHead/ProductDetailHead.scss
  src/pages/product/ProductDetailHead/ProductDetailSmallVolumeHead.jsx
  src/pages/product/ProductDetailHead/ProductDetailSmallVolumeHead.scss
Labels: Status: 수정 요청

#14 [김민성] product detail head 리뷰 컴포넌트/폴더 삭제
  src/pages/product/Product.jsx
  src/pages/product/ProductReview/ProductReview.jsx
  src/pages/product/ProductReview/ProductReview.scss
Labels: Status: 리뷰 요청

#17 [오송미] 회원가입 기능 추가완료
  .vscode/settings.json
  package-lock.json
  package.json
  src/pages/member/Login/Login.jsx
  src/pages/member/Login/Login.scss
  src/pages/member/Login/LoginForm.jsx
  src/pages/member/Signup/Signup.jsx
  src/pages/member/Signup/Signup.scss
  src/pages/member/Signup/SignupForm.jsx
Labels: Status: 리뷰 요청

#19 [감하영] TopNav의 import 위치 변경
  src/Routes.jsx
  src/components/Container/Container.jsx
  src/components/TopNav/TopNav.jsx
  src/pages/main/Main.jsx
  src/pages/member/Login/Login.jsx
  src/pages/member/Signup/Signup.jsx
  src/pages/order/Cart/Cart.scss
  src/pages/product/ProductDetailInfo/Keyword.jsx
Labels: Status: Accepted

#20 [박미정] 카테고리 페이지 리팩토링중
  src/config.js
  src/pages/category/Category.jsx
  src/pages/category/Components/ProductCard/ProductCard.jsx
Labels: Status: Accepted

#25 [감하영] config.js에 API 주소를 집약
  src/config.js
  src/pages/category/Category.jsx
  src/pages/member/Login/LoginForm.jsx
  src/pages/member/Signup/SignupForm.jsx
Labels: Status: Accepted

#23 [박미정] 네스팅 수정, 반응형, id순으로 데이터 출력하는 기능구현 완료
  src/pages/category/Category.jsx
  src/pages/category/Category.scss
  src/pages/category/Components/ProductCard/ProductCard.scss
Labels: Status: Accepted

#24 [감하영] Product 페이지의 ProductDetailInfo 영역 리팩토링 진행중
  public/data/detailData.json
  src/pages/product/ProductDetailInfo/Circle.jsx
  src/pages/product/ProductDetailInfo/Circle.scss
  src/pages/product/ProductDetailInfo/Hashtags.jsx
  src/pages/product/ProductDetailInfo/Keyword.jsx
  src/pages/product/ProductDetailInfo/Keyword.scss
  src/pages/product/ProductDetailInfo/KeywordTheme.scss
  src/pages/product/ProductDetailInfo/NoteInfo.jsx
Labels: Status: 기능 구현 중

#30 [감하영] utils.js에 가격 3자리마다 콤마 삽입 함수 추가
  src/pages/category/Components/ProductCard/ProductCard.jsx
  src/pages/order/Cart/CartTableDataRow.jsx
  src/pages/order/Cart/TotalPriceTableDataRow.jsx
  src/pages/product/ProductDetailHead/ProductDetailBigVolumeHead.jsx
  src/pages/product/ProductDetailHead/ProductDetailSmallVolumeHead.jsx
  src/utils.js
Labels: Status: 리뷰 요청

#28 [감하영] 장바구니 Read, Update API & 장바구니 컴포넌트 연계, 로딩 화면 추가, 리스트 페이지 타이틀 추가 및 일부 CSS 수정 그 외
  src/components/Loader/Loader.jsx
  src/components/Loader/Loader.scss
  src/config.js
  src/pages/category/Category.jsx
  src/pages/category/Category.scss
  src/pages/category/Components/ProductCard/ProductCard.jsx
  src/pages/category/Components/ProductCard/ProductCard.scss
  src/pages/member/Login/LoginForm.jsx
  src/pages/order/Cart/BuyButtons.jsx
  src/pages/order/Cart/Cart.jsx
  src/pages/order/Cart/CartTable.jsx
  src/pages/order/Cart/CartTable.scss
  src/pages/order/Cart/CartTableDataRow.jsx
  src/pages/order/Cart/CartTableDataRow.scss
  src/pages/order/Cart/TotalPriceTableDataRow.scss
  src/pages/product/Product.jsx
  src/pages/product/ProductDetailHead/ProductDetailBigVolumeHead.jsx
  src/pages/product/ProductDetailHead/ProductDetailSmallVolumeHead.jsx
  src/styles/_mixins.scss
  src/utils.js
Labels: Status: 리뷰 요청

#21 [김민성] 메인 페이지 리팩토링중 , MainVideo 컴포넌트 분리
  src/pages/main/Main.jsx
  src/pages/main/Main.scss
  src/pages/main/MainImage.jsx
  src/pages/main/MainImage.scss
  src/pages/main/MainImageTitle.jsx
  src/pages/main/MainImageTitle.scss
  src/pages/main/MainReview.jsx
  src/pages/main/MainReview.scss
  src/pages/main/MainReviewTotal.jsx
  src/pages/main/MainReviewTotal.scss
  src/pages/main/MainVideo.jsx
  src/pages/main/MainVideo.scss
  src/pages/product/Product.jsx
Labels: Status: 리뷰 요청
